### PR TITLE
Backtracking exercise

### PR DESCRIPTION
**Pull request by yxd3549**
Pat can't think straight

### CODE REVIEW

**Comment by GracelessGiant** [comment]
Your'e not wrong

**Review by GracelessGiant — APPROVED** [review]
Bro if code was gucci, this would be the finest of versace

**Review by eml5244 — APPROVED** [review]
tbh not gonna look too hard through this because I've already done it for a session once

**Review by pmm4516 — APPROVED** [review]
thats why adding the review was so difficult

**Pull request merged**
